# generated by fastapi-codegen:
#   filename:  PlantBreedingAPI-BrAPI-Phenotyping-2.0-resolved.yaml
#   timestamp: 2021-03-24T21:08:46+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Dict, List, Optional, Union

from pydantic import AnyUrl, BaseModel, Extra, Field, constr


class ObservationsPutRequest(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class ObservationunitsPutRequest(BaseModel):
    pass

    class Config:
        extra = Extra.allow


class Context(BaseModel):
    __root__: List[AnyUrl] = Field(
        ...,
        description='The JSON-LD Context is used to provide JSON-LD definitions to each field in a JSON object. By providing an array of context file urls, a BrAPI response object becomes JSON-LD compatible.  \n\nFor more information, see https://w3c.github.io/json-ld-syntax/#the-context',
        example=['https://brapi.org/jsonld/context/metadata.jsonld'],
        title='context',
    )


class AdditionalInfo(BaseModel):
    class Config:
        extra = Extra.allow
    #pass

    #__root__: str


class HeaderRowEnum(Enum):
    observationTimeStamp = 'observationTimeStamp'
    observationUnitDbId = 'observationUnitDbId'
    observationUnitName = 'observationUnitName'
    studyDbId = 'studyDbId'
    studyName = 'studyName'
    germplasmDbId = 'germplasmDbId'
    germplasmName = 'germplasmName'
    positionCoordinateX = 'positionCoordinateX'
    positionCoordinateY = 'positionCoordinateY'
    year = 'year'
    field = 'field'
    plot = 'plot'
    sub_plot = 'sub-plot'
    plant = 'plant'
    pot = 'pot'
    block = 'block'
    entry = 'entry'
    rep = 'rep'


class ObservationTreatment(BaseModel):
    factor: Optional[str] = Field(
        None,
        description="The type of treatment/factor. ex. 'fertilizer', 'inoculation', 'irrigation', etc\n\nMIAPPE V1.1 (DM-61) Experimental Factor type - Name/Acronym of the experimental factor.",
        example='fertilizer',
    )
    modality: Optional[str] = Field(
        None,
        description="The treatment/factor description. ex. 'low fertilizer', 'yellow rust inoculation', 'high water', etc\n\nMIAPPE V1.1 (DM-62) Experimental Factor description - Free text description of the experimental factor. This includes all relevant treatments planned and protocol planned for all the plants targeted by a given experimental factor. ",
        example='low fertilizer',
    )


class LevelName(Enum):
    study = 'study'
    field = 'field'
    entry = 'entry'
    rep = 'rep'
    block = 'block'
    sub_block = 'sub-block'
    plot = 'plot'
    sub_plot = 'sub-plot'
    plant = 'plant'
    pot = 'pot'
    sample = 'sample'


class ObservationUnitHierarchyLevel(BaseModel):
    levelName: Optional[LevelName] = Field(
        None, description='A name for this level', example='plot'
    )
    levelOrder: Optional[int] = Field(
        None,
        description="`levelOrder` defines where that level exists in the hierarchy of levels. `levelOrder`'s lower numbers are at the top of the hierarchy (ie field -> 1) and higher numbers are at the bottom of the hierarchy (ie plant -> 9).",
        example=2,
    )


class ObservationUnitLevelRelationship(ObservationUnitHierarchyLevel):
    levelCode: Optional[str] = Field(
        None,
        description='An ID code for this level tag. Identify this observation unit by each level of the hierarchy where it exists',
        example='Plot_123',
    )


class EntryType(Enum):
    CHECK = 'CHECK'
    TEST = 'TEST'
    FILLER = 'FILLER'


class PositionCoordinateXType(Enum):
    LONGITUDE = 'LONGITUDE'
    LATITUDE = 'LATITUDE'
    PLANTED_ROW = 'PLANTED_ROW'
    PLANTED_INDIVIDUAL = 'PLANTED_INDIVIDUAL'
    GRID_ROW = 'GRID_ROW'
    GRID_COL = 'GRID_COL'
    MEASURED_ROW = 'MEASURED_ROW'
    MEASURED_COL = 'MEASURED_COL'


class PositionCoordinateYType(Enum):
    LONGITUDE = 'LONGITUDE'
    LATITUDE = 'LATITUDE'
    PLANTED_ROW = 'PLANTED_ROW'
    PLANTED_INDIVIDUAL = 'PLANTED_INDIVIDUAL'
    GRID_ROW = 'GRID_ROW'
    GRID_COL = 'GRID_COL'
    MEASURED_ROW = 'MEASURED_ROW'
    MEASURED_COL = 'MEASURED_COL'


class HeaderRowEnum1(Enum):
    observationUnitDbId = 'observationUnitDbId'
    observationUnitName = 'observationUnitName'
    studyDbId = 'studyDbId'
    studyName = 'studyName'
    germplasmDbId = 'germplasmDbId'
    germplasmName = 'germplasmName'
    positionCoordinateX = 'positionCoordinateX'
    positionCoordinateY = 'positionCoordinateY'
    year = 'year'
    field = 'field'
    plot = 'plot'
    sub_plot = 'sub-plot'
    plant = 'plant'
    pot = 'pot'
    block = 'block'
    entry = 'entry'
    rep = 'rep'


class Ontology(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    authors: Optional[str] = Field(
        None,
        description="Ontology's list of authors (no specific format)",
        example='Bob Robertson, Rob Robertson',
    )
    copyright: Optional[str] = Field(
        None, description='Ontology copyright', example='Copyright 1987, Bob Robertson'
    )
    description: Optional[str] = Field(
        None,
        description='Human readable description of Ontology',
        example='This is an example ontology that does not exist',
    )
    documentationURL: Optional[AnyUrl] = Field(
        None,
        description='A URL to the human readable documentation of this object',
        example='https://wiki.brapi.org/ontology',
    )
    licence: Optional[str] = Field(
        None, description='Ontology licence', example='MIT Open source licence'
    )
    ontologyDbId: str = Field(
        ..., description='Ontology database unique identifier', example='18e186cd'
    )
    ontologyName: str = Field(
        ..., description='Ontology name', example='The Official Ontology'
    )
    version: Optional[str] = Field(
        None, description='Ontology version (no specific format)', example='V1.3.2'
    )


class SearchRequestParametersCommonCropNames(BaseModel):
    commonCropNames: Optional[List[str]] = Field(
        None,
        description='Common name for the crop which this program is for',
        example=['Tomatillo', 'Paw Paw'],
    )


class SearchRequestParametersExternalReferences(BaseModel):
    externalReferenceIDs: Optional[List[str]] = Field(
        None,
        description='List of external reference IDs. Could be a simple strings or a URIs. (use with `externalReferenceSources` parameter)',
        example=['http://purl.obolibrary.org/obo/ro.owl', '14a19841'],
    )
    externalReferenceSources: Optional[List[str]] = Field(
        None,
        description='List of identifiers for the source system or database of an external reference (use with `externalReferenceIDs` parameter)',
        example=['OBO Library', 'Field App Name'],
    )


class SearchRequestParametersGermplasm(BaseModel):
    germplasmDbIds: Optional[List[str]] = Field(
        None,
        description='List of IDs which uniquely identify germplasm to search for',
        example=['e9c6edd7', '1b1df4a6'],
    )
    germplasmNames: Optional[List[str]] = Field(
        None,
        description='List of human readable names to identify germplasm to search for',
        example=['A0000003', 'A0000477'],
    )


class SearchRequestParametersLocations(BaseModel):
    locationDbIds: Optional[List[str]] = Field(
        None,
        description='The location ids to search for',
        example=['b28911cf', '5071d1e4'],
    )
    locationNames: Optional[List[str]] = Field(
        None,
        description='A human readable names to search for',
        example=['Location Alpha', 'The Large Hadron Collider'],
    )


class SearchRequestParametersObservationVariables(BaseModel):
    observationVariableDbIds: Optional[List[str]] = Field(
        None,
        description='The DbIds of Variables to search for',
        example=['a646187d', '6d23513b'],
    )
    observationVariableNames: Optional[List[str]] = Field(
        None,
        description='The names of Variables to search for',
        example=['Plant Height in meters', 'Wheat rust score 1-5'],
    )


class SearchRequestParametersPaging(BaseModel):
    page: Optional[int] = Field(
        None,
        description="Which result page is requested. The page indexing starts at 0 (the first page is 'page'= 0). Default is `0`.",
        example=0,
    )
    pageSize: Optional[int] = Field(
        None,
        description='The size of the pages to be returned. Default is `1000`.',
        example=1000,
    )


class SearchRequestParametersPrograms(BaseModel):
    programDbIds: Optional[List[str]] = Field(
        None,
        description='A program identifier to search for',
        example=['8f5de35b', '0e2d4a13'],
    )
    programNames: Optional[List[str]] = Field(
        None,
        description='A name of a program to search for',
        example=['Better Breeding Program', 'Best Breeding Program'],
    )


class SearchRequestParametersStudies(BaseModel):
    studyDbIds: Optional[List[str]] = Field(
        None,
        description='List of study identifiers to search for',
        example=['cf6c4bd4', '691e69d6'],
    )
    studyNames: Optional[List[str]] = Field(
        None,
        description='List of study names to filter search results',
        example=['The First Bob Study 2017', 'Wheat Yield Trial 246'],
    )


class SearchRequestParametersTokenPaging(BaseModel):
    pageSize: Optional[int] = Field(
        None,
        description='The size of the pages to be returned. Default is `1000`.',
        example=1000,
    )
    pageToken: Optional[str] = Field(
        None,
        description='Used to request a specific page of data to be returned.\n\nTokenized pages are for large data sets which can not be efficiently broken into indexed pages. Use the nextPageToken and prevPageToken from a prior response to construct a query and move to the next or previous page respectively. ',
        example='33c27874',
    )


class SearchRequestParametersTrials(BaseModel):
    trialDbIds: Optional[List[str]] = Field(
        None,
        description='The ID which uniquely identifies a trial to search for',
        example=['d2593dc2', '9431a731'],
    )
    trialNames: Optional[List[str]] = Field(
        None,
        description='The human readable name of a trial to search for',
        example=['All Yield Trials 2016', 'Disease Resistance Study Comparison Group'],
    )


class Season(BaseModel):
    season: Optional[str] = Field(
        None,
        description="Name of the season. ex. 'Spring', 'Q2', 'Season A', etc.",
        example='Spring',
    )
    seasonDbId: str = Field(
        ...,
        description="The ID which uniquely identifies a season. For backward compatibility it can be a string like '2012', '1957-2004'",
        example='Spring_2018',
    )
    year: Optional[int] = Field(
        None, description='The 4 digit year of the season.', example=2018
    )


class TraitDataType(Enum):
    Code = 'Code'
    Date = 'Date'
    Duration = 'Duration'
    Nominal = 'Nominal'
    Numerical = 'Numerical'
    Ordinal = 'Ordinal'
    Text = 'Text'


class WSMIMEDataTypes(Enum):
    application_json = 'application/json'
    text_csv = 'text/csv'
    text_tsv = 'text/tsv'
    application_flapjack = 'application/flapjack'


class BasePagination(BaseModel):
    pageSize: int = Field(
        ...,
        description='The number of data elements returned, aka the size of the current page. If the requested page does not have enough elements to fill a page at the requested page size, this field should indicate the actual number of elements returned.',
        example=1000,
    )
    totalCount: Optional[int] = Field(
        None,
        description='The total number of elements that are available on the server and match the requested query parameters.',
        example=10,
    )
    totalPages: Optional[int] = Field(
        None,
        description='The total number of pages of elements available on the server. This should be calculated with the following formula. \n\ntotalPages = CEILING( totalCount / requested_page_size)',
        example=1,
    )


class DataFile(BaseModel):
    fileDescription: Optional[str] = Field(
        None,
        description='A human readable description of the file contents',
        example='This is an Excel data file',
    )
    fileMD5Hash: Optional[str] = Field(
        None,
        description='The MD5 Hash of the file contents to be used as a check sum',
        example='c2365e900c81a89cf74d83dab60df146',
    )
    fileName: Optional[str] = Field(
        None, description='The name of the file', example='datafile.xlsx'
    )
    fileSize: Optional[int] = Field(
        None, description='The size of the file in bytes', example=4398
    )
    fileType: Optional[str] = Field(
        None,
        description='The type or format of the file. Preferably MIME Type.',
        example='application/vnd.ms-excel',
    )
    fileURL: AnyUrl = Field(
        ...,
        description='The absolute URL where the file is located',
        example='https://wiki.brapi.org/examples/datafile.xlsx',
    )


class IndexPagination(BasePagination):
    currentPage: int = Field(
        ...,
        description='The index number for the returned page of data. This should always match the requested page number or the default page (0).',
        example=0,
    )


class Position(BaseModel):
    __root__: List[float] = Field(
        ...,
        description='A single position',
        example=[-76.506042, 42.417373, 123],
        min_items=2,
    )


class MessageType(Enum):
    DEBUG = 'DEBUG'
    ERROR = 'ERROR'
    WARNING = 'WARNING'
    INFO = 'INFO'


class Status(BaseModel):
    message: str = Field(
        ...,
        description='A short message concerning the status of this request/response',
        example='Request accepted, response successful',
    )
    messageType: MessageType = Field(
        ..., description='The logging level for the attached message', example='INFO'
    )


class TokenPagination(BasePagination):
    currentPageToken: Optional[str] = Field(
        None,
        description='The string token used to query the current page of data.',
        example='48bc6ac1',
    )
    nextPageToken: str = Field(
        ...,
        description='The string token used to query the next page of data.',
        example='cb668f63',
    )
    prevPageToken: Optional[str] = Field(
        None,
        description='The string token used to query the previous page of data.',
        example='9659857e',
    )


class EventEventParameters(BaseModel):
    key: Optional[str] = Field(
        None,
        description='Specifies the relationship between the event and the given property. E.g. fertilizer, operator',
        example='operator',
    )
    rdfValue: Optional[str] = Field(
        None,
        description='The type of the value given above, e.g. http://xmlns.com/foaf/0.1/Agent',
        example='http://xmlns.com/foaf/0.1/Agent',
    )
    value: Optional[str] = Field(
        None,
        description='The value of the property for this event. E.g. nitrogen, John Doe',
        example='Bob Robertson',
    )


class ExternalReferencesInner(BaseModel):
    referenceID: Optional[str] = Field(
        None,
        description='The external reference ID. Could be a simple string or a URI.',
    )
    referenceSource: Optional[str] = Field(
        None,
        description='An identifier for the source system or database of this reference',
    )


class ObservationTableObservationVariables(BaseModel):
    observationVariableDbId: Optional[str] = Field(
        None, description='Variable unique identifier', example='367aa1a9'
    )
    observationVariableName: Optional[str] = Field(
        None, description='Variable name (usually a short name)', example='Plant height'
    )


class Type(Enum):
    OBO = 'OBO'
    RDF = 'RDF'
    WEBPAGE = 'WEBPAGE'


class OntologyReferenceDocumentationLinks(BaseModel):
    URL: Optional[AnyUrl] = Field(None, example='http://purl.obolibrary.org/obo/ro.owl')
    type: Optional[Type] = Field(None, example='OBO')


class ScaleBaseClassValidValuesCategories(BaseModel):
    label: Optional[str] = Field(None, description='A text label for a category')
    value: Optional[str] = Field(None, description='The actual value for a category')


class ScaleBaseClassValidValues(BaseModel):
    categories: Optional[List[ScaleBaseClassValidValuesCategories]] = Field(
        None,
        description='List of possible values with optional labels',
        example=[
            {'label': 'low', 'value': '0'},
            {'label': 'medium', 'value': '5'},
            {'label': 'high', 'value': '10'},
        ],
    )
    max: Optional[int] = Field(
        None,
        description='Maximum value (used for field data capture control).',
        example=9999,
    )
    min: Optional[int] = Field(
        None,
        description='Minimum value (used for data capture control) for numerical and date scales',
        example=2,
    )


class ObservationLevelListResponseResult(BaseModel):
    data: List[ObservationUnitHierarchyLevel] = Field(
        ...,
        example=[
            {'levelName': 'field', 'levelOrder': 0},
            {'levelName': 'block', 'levelOrder': 1},
            {'levelName': 'plot', 'levelOrder': 2},
            {'levelName': 'sub-plot', 'levelOrder': 3},
            {'levelName': 'plant', 'levelOrder': 4},
        ],
    )


class OntologyListResponseResult(BaseModel):
    data: List[Ontology]


class Field202AcceptedSearchResponseResult(BaseModel):
    searchResultsDbId: Optional[str] = Field(None, example='551ae08c')


class Event(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    date: Optional[List[datetime]] = Field(
        None,
        description='A list of dates when the event occurred\n\nMIAPPE V1.1 (DM-68) Event date - Date and time of the event.',
        example=['2018-10-08T18:15:11Z', '2018-11-09T18:16:12Z'],
    )
    eventDbId: str = Field(
        ..., description='Internal database identifier', example='8566d4cb'
    )
    eventDescription: Optional[str] = Field(
        None,
        description='A detailed, human-readable description of this event\n\nMIAPPE V1.1 (DM-67) Event description - Description of the event, including details such as amount applied and possibly duration of the event. ',
        example='A set of plots was watered',
    )
    eventParameters: Optional[List[EventEventParameters]] = Field(
        None,
        description='A list of objects describing additional event parameters. Each of the following accepts a human-readable value or URI',
        example=[
            {
                'key': 'http://www.example.fr/vocabulary/2018#hasContact,',
                'value': 'http://www.example.fr/id/agent/marie,',
                'valueRdfType': 'http://xmlns.com/foaf/0.1/Agent,',
            },
            {'key': 'fertilizer', 'value': 'nitrogen'},
        ],
    )
    eventType: str = Field(
        ...,
        description='General category for this event (e.g. Sowing, Watering, Rain). Each eventType should correspond to exactly one eventTypeDbId, if provided.\n\nMIAPPE V1.1 (DM-65) Event type - Short name of the event.',
        example='Watering',
    )
    eventTypeDbId: Optional[str] = Field(
        None,
        description='An identifier for this event type, in the form of an ontology class reference\n\nMIAPPE V1.1 (DM-66) Event accession number - Accession number of the event type in a suitable controlled vocabulary (Crop Ontology).',
        example='4e7d691e',
    )
    observationUnitDbIds: Optional[List[str]] = Field(
        None,
        description='A list of the affected observation units. If this parameter is not given, it is understood that the event affected all units in the study',
        example=['8439eaff', 'd7682e7a', '305ae51c'],
    )
    studyDbId: Optional[str] = Field(
        None, description='The study in which the event occurred', example='2cc2001f'
    )


class ExternalReferences(BaseModel):
    __root__: List[ExternalReferencesInner] = Field(
        ...,
        description='An array of external reference ids. These are references to this piece of data in an external system. Could be a simple string or a URI.',
        example=[
            {'referenceID': 'doi:10.155454/12341234', 'referenceSource': 'DOI'},
            {
                'referenceID': 'http://purl.obolibrary.org/obo/ro.owl',
                'referenceSource': 'OBO Library',
            },
            {
                'referenceID': '75a50e76',
                'referenceSource': 'Remote Data Collection Upload Tool',
            },
        ],
        title='ExternalReferences',
    )


class ObservationNewRequest(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    collector: Optional[str] = Field(
        None,
        description='The name or identifier of the entity which collected the observation',
        example='917d3ae0',
    )
    externalReferences: Optional[ExternalReferences] = None
    germplasmDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies a germplasm',
        example='2408ab11',
    )
    germplasmName: Optional[str] = Field(
        None,
        description='Name of the germplasm. It can be the preferred name and does not have to be unique.',
        example='A0000003',
    )
    observationTimeStamp: Optional[datetime] = Field(
        None, description='The date and time when this observation was made'
    )
    observationUnitDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies an observation unit',
        example='598111d4',
    )
    observationUnitName: Optional[str] = Field(
        None,
        description='A human readable name for an observation unit',
        example='Plot 1',
    )
    observationVariableDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies an observation variable',
        example='c403d107',
    )
    observationVariableName: Optional[str] = Field(
        None,
        description='A human readable name for an observation variable',
        example='Plant Height in meters',
    )
    season: Optional[Season] = None
    studyDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies a study within the given database server',
        example='ef2829db',
    )
    uploadedBy: Optional[str] = Field(
        None,
        description='The name or id of the user who uploaded the observation to the database system',
        example='a2f7f60b',
    )
    value: Optional[str] = Field(
        None,
        description='The value of the data collected as an observation',
        example='2.3',
    )


class ObservationSearchRequest(
    SearchRequestParametersPaging,
    SearchRequestParametersPrograms,
    SearchRequestParametersTrials,
    SearchRequestParametersStudies,
    SearchRequestParametersGermplasm,
    SearchRequestParametersLocations,
    SearchRequestParametersObservationVariables,
    SearchRequestParametersExternalReferences,
):
    observationDbIds: Optional[List[str]] = Field(
        None,
        description='The unique id of an Observation',
        example=['6a4a59d8', '3ff067e0'],
    )
    observationLevelRelationships: Optional[
        List[ObservationUnitLevelRelationship]
    ] = Field(
        None,
        description='Searches for values in ObservationUnit->observationUnitPosition->observationLevelRelationships',
        example=[{'levelCode': 'Field_1', 'levelName': 'field'}],
    )
    observationLevels: Optional[List[ObservationUnitLevelRelationship]] = Field(
        None,
        description='Searches for values in ObservationUnit->observationUnitPosition->observationLevel',
        example=[
            {'levelCode': 'Plot_123', 'levelName': 'plot'},
            {'levelCode': 'Plot_456', 'levelName': 'plot'},
            {'levelCode': 'Plot_789', 'levelName': 'plot'},
        ],
    )
    observationTimeStampRangeEnd: Optional[datetime] = Field(
        None, description='Timestamp range end'
    )
    observationTimeStampRangeStart: Optional[datetime] = Field(
        None, description='Timestamp range start'
    )
    observationUnitDbIds: Optional[List[str]] = Field(
        None,
        description='The unique id of an Observation Unit',
        example=['76f559b5', '066bc5d3'],
    )
    seasonDbIds: Optional[List[str]] = Field(
        None,
        description='The year or Phenotyping campaign of a multi-annual study (trees, grape, ...)',
        example=['Spring 2018', 'Season A'],
    )


class ObservationTable(BaseModel):
    data: Optional[List[List[str]]] = Field(
        None,
        description='Matrix of observation data recorded for different observation variables across different observation units',
        example=[
            [
                '2019-09-10T18:13:27.223Z',
                'f3a8a3db',
                'Plant Alpha',
                '0fe3e48b',
                '2017 Plant Study',
                '06307ec0',
                'A0043001',
                '76.50106681',
                '42.44409301',
                '2017',
                'Field_1',
                'Plot_11',
                'SubPlot_111',
                'Plant_1111',
                'Pot_1111',
                'Block_11',
                'Entry_11',
                'Rep_11',
                '25.3',
                '',
                '',
                '',
            ],
            [
                '2019-09-10T18:14:27.223Z',
                'f3a8a3db',
                'Plant Alpha',
                '0fe3e48b',
                '2017 Plant Study',
                '06307ec0',
                'A0043001',
                '76.50106681',
                '42.44409301',
                '2017',
                'Field_1',
                'Plot_11',
                'SubPlot_111',
                'Plant_1111',
                'Pot_1111',
                'Block_11',
                'Entry_11',
                'Rep_11',
                '',
                '3',
                '',
                '',
            ],
            [
                '2019-09-10T18:15:54.868Z',
                '05d1b011',
                'Plant Beta',
                '0fe3e48b',
                '2017 Plant Study',
                '59d435cd',
                'A0043002',
                '76.50106683',
                '42.44409301',
                '2017',
                'Field_1',
                'Plot_11',
                'SubPlot_112',
                'Plant_1122',
                'Pot_1122',
                'Block_11',
                'Entry_11',
                'Rep_12',
                '27.9',
                '',
                '',
                '',
            ],
            [
                '2019-09-10T18:16:54.868Z',
                '05d1b011',
                'Plant Beta',
                '0fe3e48b',
                '2017 Plant Study',
                '59d435cd',
                'A0043002',
                '76.50106683',
                '42.44409301',
                '2017',
                'Field_1',
                'Plot_11',
                'SubPlot_112',
                'Plant_1122',
                'Pot_1122',
                'Block_11',
                'Entry_11',
                'Rep_12',
                '',
                '1',
                '',
                '',
            ],
            [
                '2019-09-10T18:17:34.433Z',
                '67e2d87c',
                'Plant Gamma',
                '0fe3e48b',
                '2017 Plant Study',
                '06307ec0',
                'A0043001',
                '76.50106681',
                '42.44409356',
                '2017',
                'Field_1',
                'Plot_12',
                'SubPlot_123',
                'Plant_1233',
                'Pot_1233',
                'Block_12',
                'Entry_12',
                'Rep_11',
                '',
                '3',
                '',
                '',
            ],
            [
                '2019-09-10T18:18:34.433Z',
                '67e2d87c',
                'Plant Gamma',
                '0fe3e48b',
                '2017 Plant Study',
                '06307ec0',
                'A0043001',
                '76.50106681',
                '42.44409356',
                '2017',
                'Field_1',
                'Plot_12',
                'SubPlot_123',
                'Plant_1233',
                'Pot_1233',
                'Block_12',
                'Entry_12',
                'Rep_11',
                '25.5',
                '',
                '',
                '',
            ],
            [
                '2019-09-10T18:19:15.629Z',
                'd98d0d4c',
                'Plant Epsilon',
                '0fe3e48b',
                '2017 Plant Study',
                '59d435cd',
                'A0043002',
                '76.50106683',
                '42.44409356',
                '2017',
                'Field_1',
                'Plot_12',
                'SubPlot_124',
                'Plant_1244',
                'Pot_1244',
                'Block_12',
                'Entry_12',
                'Rep_12',
                '28.9',
                '',
                '',
                '',
            ],
            [
                '2019-09-10T18:20:15.629Z',
                'd98d0d4c',
                'Plant Epsilon',
                '0fe3e48b',
                '2017 Plant Study',
                '59d435cd',
                'A0043002',
                '76.50106683',
                '42.44409356',
                '2017',
                'Field_1',
                'Plot_12',
                'SubPlot_124',
                'Plant_1244',
                'Pot_1244',
                'Block_12',
                'Entry_12',
                'Rep_12',
                '',
                '0',
                '',
                '',
            ],
        ],
    )
    headerRow: Optional[List[HeaderRowEnum]] = Field(
        None,
        description='<p>The table is REQUIRED to have the following columns</p>\n<ul>\n  <li>observationUnitDbId - Each row is related to one Observation Unit</li>\n  <li>observationTimeStamp - Each row is has a time stamp for when the observation was taken</li>\n  <li>At least one column with an observationVariableDbId</li>\n</ul>\n<p>The table may have any or all of the following OPTIONAL columns. Included columns are decided by the server developer</p>\n<ul>\n  <li>observationUnitName</li>\n  <li>studyDbId</li>\n  <li>studyName</li>\n  <li>germplasmDbId</li>\n  <li>germplasmName</li>\n  <li>positionCoordinateX</li>\n  <li>positionCoordinateY</li>\n  <li>year</li>\n</ul>\n<p>The table also may have any number of Observation Unit Hierarchy Level columns. For example:</p>\n<ul>\n  <li>field</li>\n  <li>plot</li>\n  <li>sub-plot</li>\n  <li>plant</li>\n  <li>pot</li>\n  <li>block</li>\n  <li>entry</li>\n  <li>rep</li>\n</ul>\n<p>The JSON representation provides a pair of extra arrays for defining the headers of the table. \nThe first array "headerRow" will always contain "observationUnitDbId" and any or all of the OPTIONAL column header names. \nThe second array "observationVariables" contains the names and DbIds for the Observation Variables represented in the table. \nBy appending the two arrays, you can construct the complete header row of the table. </p>',
        example=[
            'observationTimeStamp',
            'observationUnitDbId',
            'observationUnitName',
            'studyDbId',
            'studyName',
            'germplasmDbId',
            'germplasmName',
            'positionCoordinateX',
            'positionCoordinateY',
            'year',
            'field',
            'plot',
            'sub-plot',
            'plant',
            'pot',
            'block',
            'entry',
            'rep',
        ],
    )
    observationVariables: Optional[List[ObservationTableObservationVariables]] = Field(
        None,
        description="The list of observation variables which have values recorded for them in the data matrix. Append to the 'headerRow' for complete header row of the table.",
        example=[
            {
                'observationVariableDbId': '367aa1a9',
                'observationVariableName': 'Plant height',
            },
            {
                'observationVariableDbId': '2acb934c',
                'observationVariableName': 'Carotenoid',
            },
            {
                'observationVariableDbId': '85a21ce1',
                'observationVariableName': 'Root color',
            },
            {
                'observationVariableDbId': '46f590e5',
                'observationVariableName': 'Virus severity',
            },
        ],
    )


class ObservationUnitSearchRequest(
    SearchRequestParametersPaging,
    SearchRequestParametersPrograms,
    SearchRequestParametersTrials,
    SearchRequestParametersStudies,
    SearchRequestParametersLocations,
    SearchRequestParametersGermplasm,
    SearchRequestParametersObservationVariables,
    SearchRequestParametersExternalReferences,
):
    includeObservations: Optional[bool] = Field(
        None,
        description='Use this parameter to include a list of observations embedded in each ObservationUnit object. \n\nCAUTION - Use this parameter at your own risk. It may return large, unpaginated lists of observation data. Only set this value to True if you are sure you need to.',
        example=False,
    )
    observationLevelRelationships: Optional[
        List[ObservationUnitLevelRelationship]
    ] = Field(
        None,
        description='Searches for values in ObservationUnit->observationUnitPosition->observationLevelRelationships',
        example=[{'levelCode': 'Field_1', 'levelName': 'field'}],
    )
    observationLevels: Optional[List[ObservationUnitLevelRelationship]] = Field(
        None,
        description='Searches for values in ObservationUnit->observationUnitPosition->observationLevel',
        example=[
            {'levelCode': 'Plot_123', 'levelName': 'plot'},
            {'levelCode': 'Plot_456', 'levelName': 'plot'},
            {'levelCode': 'Plot_789', 'levelName': 'plot'},
        ],
    )
    observationUnitDbIds: Optional[List[str]] = Field(
        None,
        description='The unique id of an observation unit',
        example=['66bab7e3', '0e5e7f99'],
    )


class ObservationUnitTable(BaseModel):
    data: Optional[List[List[str]]] = Field(
        None,
        description='Matrix of observation data recorded for different observation variables across different observation units',
        example=[
            [
                'f3a8a3db',
                'Plant Alpha',
                '0fe3e48b',
                '2017 Plant Study',
                '06307ec0',
                'A0043001',
                '76.50106681',
                '42.44409301',
                '2017',
                'Field_1',
                'Plot_11',
                'SubPlot_111',
                'Plant_1111',
                'Pot_1111',
                'Block_11',
                'Entry_11',
                'Rep_11',
                '25.3',
                '3',
                '50.75',
            ],
            [
                '05d1b011',
                'Plant Beta',
                '0fe3e48b',
                '2017 Plant Study',
                '59d435cd',
                'A0043002',
                '76.50106683',
                '42.44409301',
                '2017',
                'Field_1',
                'Plot_11',
                'SubPlot_112',
                'Plant_1122',
                'Pot_1122',
                'Block_11',
                'Entry_11',
                'Rep_12',
                '27.9',
                '1',
                '45.345',
            ],
            [
                '67e2d87c',
                'Plant Gamma',
                '0fe3e48b',
                '2017 Plant Study',
                '06307ec0',
                'A0043001',
                '76.50106681',
                '42.44409356',
                '2017',
                'Field_1',
                'Plot_12',
                'SubPlot_123',
                'Plant_1233',
                'Pot_1233',
                'Block_12',
                'Entry_12',
                'Rep_11',
                '25.5',
                '3',
                '50.76',
            ],
            [
                'd98d0d4c',
                'Plant Epsilon',
                '0fe3e48b',
                '2017 Plant Study',
                '59d435cd',
                'A0043002',
                '76.50106683',
                '42.44409356',
                '2017',
                'Field_1',
                'Plot_12',
                'SubPlot_124',
                'Plant_1244',
                'Pot_1244',
                'Block_12',
                'Entry_12',
                'Rep_12',
                '28.9',
                '0',
                '46.5',
            ],
        ],
    )
    headerRow: Optional[List[HeaderRowEnum1]] = Field(
        None,
        description='<p>The table is REQUIRED to have the following columns</p>\n<ul>\n  <li>observationUnitDbId - Each row is related to one Observation Unit</li>\n  <li>At least one column with an observationVariableDbId</li>\n</ul>\n<p>The table may have any or all of the following OPTIONAL columns. Included columns are decided by the server developer</p>\n<ul>\n  <li>observationUnitName</li>\n  <li>studyDbId</li>\n  <li>studyName</li>\n  <li>germplasmDbId</li>\n  <li>germplasmName</li>\n  <li>positionCoordinateX</li>\n  <li>positionCoordinateY</li>\n  <li>year</li>\n</ul>\n<p>The table also may have any number of Observation Unit Hierarchy Level columns. For example:</p>\n<ul>\n  <li>field</li>\n  <li>plot</li>\n  <li>sub-plot</li>\n  <li>plant</li>\n  <li>pot</li>\n  <li>block</li>\n  <li>entry</li>\n  <li>rep</li>\n</ul>\n<p>The JSON representation provides a pair of extra arrays for defining the headers of the table. \nThe first array "headerRow" will always contain "observationUnitDbId" and any or all of the OPTIONAL column header names. \nThe second array "observationVariables" contains the names and DbIds for the Observation Variables represented in the table. \nBy appending the two arrays, you can construct the complete header row of the table. </p>',
        example=[
            'observationUnitDbId',
            'observationUnitName',
            'studyDbId',
            'studyName',
            'germplasmDbId',
            'germplasmName',
            'positionCoordinateX',
            'positionCoordinateY',
            'year',
            'field',
            'plot',
            'sub-plot',
            'plant',
            'pot',
            'block',
            'entry',
            'rep',
        ],
    )
    observationVariables: Optional[List[ObservationTableObservationVariables]] = Field(
        None,
        description="The list of observation variables which have values recorded for them in the data matrix. Append to the 'headerRow' for complete header row of the table.",
        example=[
            {
                'observationVariableDbId': '367aa1a9',
                'observationVariableName': 'Plant height',
            },
            {
                'observationVariableDbId': '2acb934c',
                'observationVariableName': 'Carotenoid',
            },
            {
                'observationVariableDbId': '85a21ce1',
                'observationVariableName': 'Root color',
            },
            {
                'observationVariableDbId': '46f590e5',
                'observationVariableName': 'Virus severity',
            },
        ],
    )


class ObservationVariableSearchRequest(
    SearchRequestParametersPaging, SearchRequestParametersExternalReferences
):
    dataTypes: Optional[List[TraitDataType]] = Field(
        None,
        description='List of scale data types to filter search results',
        example=['Numerical', 'Ordinal', 'Text'],
    )
    methodDbIds: Optional[List[str]] = Field(
        None,
        description='List of methods to filter search results',
        example=['07e34f83', 'd3d5517a'],
    )
    observationVariableDbIds: Optional[List[str]] = Field(
        None,
        description='List of observation variable IDs to search for',
        example=['2ef15c9f', '318e7f7d'],
    )
    observationVariableNames: Optional[List[str]] = Field(
        None,
        description='List of human readable observation variable names to search for',
        example=['Plant Height 1', 'Root Color'],
    )
    ontologyDbIds: Optional[List[str]] = Field(
        None,
        description='List of ontology IDs to search for',
        example=['f44f7b23', 'a26b576e'],
    )
    scaleDbIds: Optional[List[str]] = Field(
        None,
        description='List of scales to filter search results',
        example=['a13ecffa', '7e1afe4f'],
    )
    studyDbId: Optional[List[str]] = Field(
        None,
        description='The unique ID of a studies to filter on',
        example=['5bcac0ae', '7f48e22d'],
    )
    traitClasses: Optional[List[str]] = Field(
        None,
        description='List of trait classes to filter search results',
        example=['morphological', 'phenological', 'agronomical'],
    )
    traitDbIds: Optional[List[str]] = Field(
        None,
        description='List of trait unique ID to filter search results',
        example=['ef81147b', '78d82fad'],
    )


class OntologyReference(BaseModel):
    documentationLinks: Optional[List[OntologyReferenceDocumentationLinks]] = Field(
        None, description='links to various ontology documentation'
    )
    ontologyDbId: str = Field(
        ..., description='Ontology database unique identifier', example='6b071868'
    )
    ontologyName: str = Field(
        ..., description='Ontology name', example='The Crop Ontology'
    )
    version: Optional[str] = Field(
        None, description='Ontology version (no specific format)', example='7.2.3'
    )


class ScaleBaseClass(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    dataType: Optional[TraitDataType] = None
    decimalPlaces: Optional[int] = Field(
        None,
        description='For numerical, number of decimal places to be reported',
        example=2,
    )
    externalReferences: Optional[ExternalReferences] = None
    ontologyReference: Optional[OntologyReference] = None
    scaleName: str = Field(
        ...,
        description='Name of the scale\n\nMIAPPE V1.1 (DM-92) Scale Name of the scale associated with the variable',
        example='Meters',
    )
    validValues: Optional[ScaleBaseClassValidValues] = None


class ScaleNewRequest(BaseModel):
    __root__: ScaleBaseClass


class TraitBaseClass(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    alternativeAbbreviations: Optional[List[str]] = Field(
        None,
        description='Other frequent abbreviations of the trait, if any. These abbreviations do not have to follow a convention',
        example=['H', 'PH', 'H1'],
    )
    attribute: Optional[str] = Field(
        None,
        description='A trait can be decomposed as "Trait" = "Entity" + "Attribute", the attribute is the observed feature (or characteristic) of the entity e.g., for "grain colour", attribute = "colour"',
        example='height',
    )
    entity: Optional[str] = Field(
        None,
        description='A trait can be decomposed as "Trait" = "Entity" + "Attribute", the entity is the part of the plant that the trait refers to e.g., for "grain colour", entity = "grain"',
        example='Stalk',
    )
    externalReferences: Optional[ExternalReferences] = None
    mainAbbreviation: Optional[str] = Field(
        None,
        description='Main abbreviation for trait name. (examples: "Carotenoid content" => "CC")',
        example='PH',
    )
    ontologyReference: Optional[OntologyReference] = None
    status: Optional[str] = Field(
        None,
        description='Trait status (examples: "recommended", "obsolete", "legacy", etc.)',
        example='recommended',
    )
    synonyms: Optional[List[str]] = Field(
        None,
        description='Other trait names',
        example=['Height', 'Plant Height', 'Stalk Height', 'Canopy Height'],
    )
    traitClass: Optional[str] = Field(
        None,
        description='Trait class. (examples: "morphological", "phenological", "agronomical", "physiological", "abiotic stress", "biotic stress", "biochemical", "quality traits", "fertility", etc.)',
        example='phenological',
    )
    traitDescription: Optional[str] = Field(
        None,
        description='The description of a trait',
        example='The height of the plant',
    )
    traitName: Optional[str] = Field(
        None,
        description='The human readable name of a trait\n\nMIAPPE V1.1 (DM-86) Trait - Name of the (plant or environmental) trait under observation',
        example='Height',
    )


class TraitNewRequest(BaseModel):
    __root__: TraitBaseClass


class Scale1(ScaleBaseClass):
    scaleDbId: str = Field(
        ...,
        description='Unique identifier of the scale. If left blank, the upload system will automatically generate a scale ID.',
        example='af730171',
    )


class Trait1(TraitBaseClass):
    traitDbId: Optional[str] = Field(
        None, description='The ID which uniquely identifies a trait', example='9b2e34f5'
    )


class LinearRing(BaseModel):
    __root__: List[Position] = Field(
        ...,
        description='An array of at least four positions where the first equals the last',
        example=[
            [-77.456654, 42.241133, 494],
            [-75.414133, 41.508282, 571],
            [-76.506042, 42.417373, 123],
            [-77.456654, 42.241133, 346],
        ],
        min_items=4,
    )


class MetadataBase(BaseModel):
    datafiles: Optional[List[DataFile]] = Field(
        None,
        description='The datafiles contains a list of file URLs and metadata. \nThese files contain additional information related to the returned object and can be retrieved by a subsequent call. \nThis could be a supplementary data file, an informational file, the uploaded file where the data originated from, a generated file representing the whole dataset in a particular format, or any other related file. ',
    )
    status: Optional[List[Status]] = Field(
        None,
        description='The status field contains a list of informational status messages from the server. \nIf no status is reported, an empty list should be returned. See Error Reporting for more information.',
    )


class MetadataTokenPagination(MetadataBase):
    pagination: Optional[TokenPagination] = None


class PointGeometry(BaseModel):
    coordinates: Optional[Position] = None
    type: Optional[str] = Field(
        'Point', description='The literal string "Point"', example='Point'
    )


class Polygon(BaseModel):
    __root__: List[LinearRing] = Field(
        ...,
        description='An array of linear rings',
        example=[
            [
                [-77.456654, 42.241133, 494],
                [-75.414133, 41.508282, 571],
                [-76.506042, 42.417373, 123],
                [-77.456654, 42.241133, 346],
            ]
        ],
    )


class PolygonGeometry(BaseModel):
    coordinates: Optional[Polygon] = None
    type: Optional[str] = Field(
        'Polygon', description='The literal string "Polygon"', example='Polygon'
    )


class EventsResponseResult(BaseModel):
    data: List[Event]


class MethodBaseClass(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    bibliographicalReference: Optional[str] = Field(
        None,
        description='Bibliographical reference describing the method.\n\nMIAPPE V1.1 (DM-91) Reference associated to the method - URI/DOI of reference describing the method.',
        example='Smith, 1893, Really Cool Paper, Popular Journal',
    )
    description: Optional[str] = Field(
        None,
        description='Method description\n\nMIAPPE V1.1 (DM-90) Method description - Textual description of the method, which may extend a method defined in an external reference with specific parameters, e.g. growth stage, inoculation precise organ (leaf number)',
        example='A measuring tape was used',
    )
    externalReferences: Optional[ExternalReferences] = None
    formula: Optional[str] = Field(
        None,
        description='For computational methods i.e., when the method consists in assessing the trait by computing measurements, write the generic formula used for the calculation',
        example='a^2 + b^2 = c^2',
    )
    methodClass: Optional[str] = Field(
        None,
        description='Method class (examples: "Measurement", "Counting", "Estimation", "Computation", etc.)',
        example='Measurement',
    )
    methodName: Optional[str] = Field(
        None,
        description='Human readable name for the method\n\nMIAPPE V1.1 (DM-88) Method  Name of the method of observation',
        example='Measuring Tape',
    )
    ontologyReference: Optional[OntologyReference] = None


class MethodNewRequest(BaseModel):
    __root__: MethodBaseClass


class Observation(ObservationNewRequest):
    observationDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies an observation',
        example='ef24b615',
    )


class Scale(ScaleBaseClass):
    scaleDbId: str = Field(
        ...,
        description='Unique identifier of the scale. If left blank, the upload system will automatically generate a scale ID.',
        example='af730171',
    )


class Trait(TraitBaseClass):
    traitDbId: Optional[str] = Field(
        None, description='The ID which uniquely identifies a trait', example='9b2e34f5'
    )


class Method1(MethodBaseClass):
    methodDbId: Optional[str] = Field(
        None, description='Method unique identifier', example='0adb2764'
    )


class VariableBaseClass(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    commonCropName: Optional[str] = Field(
        None, description='Crop name (examples: "Maize", "Wheat")', example='Maize'
    )
    contextOfUse: Optional[List[str]] = Field(
        None,
        description='Indication of how trait is routinely used. (examples: ["Trial evaluation", "Nursery evaluation"])',
        example=['Trial evaluation', 'Nursery evaluation'],
    )
    defaultValue: Optional[str] = Field(
        None,
        description='Variable default value. (examples: "red", "2.3", etc.)',
        example='2.0',
    )
    documentationURL: Optional[AnyUrl] = Field(
        None,
        description='A URL to the human readable documentation of this object',
        example='https://wiki.brapi.org/documentation.html',
    )
    externalReferences: Optional[ExternalReferences] = None
    growthStage: Optional[str] = Field(
        None,
        description='Growth stage at which measurement is made (examples: "flowering")',
        example='flowering',
    )
    institution: Optional[str] = Field(
        None,
        description='Name of institution submitting the variable',
        example='The BrAPI Institute',
    )
    language: Optional[str] = Field(
        None,
        description='2 letter ISO 639-1 code for the language of submission of the variable.',
        example='en',
    )
    method: Method1
    ontologyReference: Optional[OntologyReference] = None
    scale: Scale1
    scientist: Optional[str] = Field(
        None,
        description='Name of scientist submitting the variable.',
        example='Dr. Bob Robertson',
    )
    status: Optional[str] = Field(
        None,
        description='Variable status. (examples: "recommended", "obsolete", "legacy", etc.)',
        example='recommended',
    )
    submissionTimestamp: Optional[datetime] = Field(
        None, description='Timestamp when the Variable was added (ISO 8601)'
    )
    synonyms: Optional[List[str]] = Field(
        None,
        description='Other variable names',
        example=['Maize Height', 'Stalk Height', 'Corn Height'],
    )
    trait: Trait1


class GeoJSON(BaseModel):
    geometry: Optional[Union[PointGeometry, PolygonGeometry]] = Field(
        None,
        description='A geometry as defined by GeoJSON (RFC 7946). In this context, only Point or Polygon geometry are allowed.',
        example={'coordinates': [-76.506042, 42.417373, 123], 'type': 'Point'},
        title='GeoJSON Geometry',
    )
    type: Optional[str] = Field(
        'Feature', description='The literal string "Feature"', example='Feature'
    )


class GeoJSONSearchArea(GeoJSON):
    pass


class Metadata(MetadataBase):
    pagination: Optional[IndexPagination] = None


class EventsResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: EventsResponseResult


class ObservationLevelListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationLevelListResponseResult


class ObservationTableResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationTable


class ObservationSingleResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: Observation


class ObservationUnitTableResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationUnitTable


class OntologyListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: OntologyListResponseResult


class ScaleSingleResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: Scale


class Field202AcceptedSearchResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Optional[Metadata] = None
    result: Optional[Field202AcceptedSearchResponseResult] = None


class TraitSingleResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: Trait


class ObservationListResponseResult(BaseModel):
    data: List[Observation]


class ScaleListResponseResult(BaseModel):
    data: List[Scale]


class TraitListResponseResult(BaseModel):
    data: List[Trait]


class ImageNewRequest(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = None
    copyright: Optional[str] = Field(
        None,
        description="The copyright information of this image. Example 'Copyright 2018 Bob Robertson'",
        example='Copyright 2018 Bob Robertson',
    )
    description: Optional[str] = Field(
        None,
        description='The human readable description of an image.',
        example='This is a picture of a tomato',
    )
    descriptiveOntologyTerms: Optional[List[str]] = Field(
        None,
        description='A list of terms to formally describe the image. Each item could be a simple Tag, an Ontology reference Id, or a full ontology URL.',
        example=['doi:10.1002/0470841559', 'Red', 'ncbi:0300294'],
    )
    externalReferences: Optional[ExternalReferences] = None
    imageFileName: Optional[str] = Field(
        None,
        description="The name of the image file. Might be the same as 'imageName', but could be different.",
        example='image_0000231.jpg',
    )
    imageFileSize: Optional[int] = Field(
        None, description='The size of the image in Bytes.', example=50000
    )
    imageHeight: Optional[int] = Field(
        None, description='The height of the image in Pixels.', example=550
    )
    imageLocation: Optional[GeoJSON] = None
    imageName: Optional[str] = Field(
        None,
        description="The human readable name of an image. Might be the same as 'imageFileName', but could be different.",
        example='Tomato Image 1',
    )
    imageTimeStamp: Optional[datetime] = Field(
        None, description='The date and time the image was taken'
    )
    imageURL: Optional[str] = Field(
        None,
        description='The complete, absolute URI path to the image file. Images might be stored on a different host or path than the BrAPI web server.',
        example='https://wiki.brapi.org/images/tomato',
    )
    imageWidth: Optional[int] = Field(
        None, description='The width of the image in Pixels.', example=700
    )
    mimeType: Optional[constr(regex=r'image/.*')] = Field(
        None,
        description="The file type of the image. Examples 'image/jpeg', 'image/png', 'image/svg', etc",
        example='image/jpeg',
    )
    observationDbIds: Optional[List[str]] = Field(
        None,
        description='A list of observation Ids this image is associated with, if applicable.',
        example=['d05dd235', '8875177d', 'c08e81b6'],
    )
    observationUnitDbId: Optional[str] = Field(
        None,
        description='The related observation unit identifier, if relevant.',
        example='b7e690b6',
    )


class ImageSearchRequest(
    SearchRequestParametersPaging, SearchRequestParametersExternalReferences
):
    descriptiveOntologyTerms: Optional[List[str]] = Field(
        None,
        description='A list of terms to formally describe the image to search for. Each item could be a simple Tag, an Ontology reference Id, or a full ontology URL.',
        example=['doi:10.1002/0470841559', 'Red', 'ncbi:0300294'],
    )
    imageDbIds: Optional[List[str]] = Field(
        None,
        description='A list of image Ids to search for',
        example=['564b64a6', '0d122d1d'],
    )
    imageFileNames: Optional[List[str]] = Field(
        None,
        description='Image file names to search for.',
        example=['image_01032019.jpg', 'picture_field_1234.jpg'],
    )
    imageFileSizeMax: Optional[int] = Field(
        None, description='A maximum image file size to search for.', example=20000000
    )
    imageFileSizeMin: Optional[int] = Field(
        None, description='A minimum image file size to search for.', example=1000
    )
    imageHeightMax: Optional[int] = Field(
        None, description='A maximum image height to search for.', example=1080
    )
    imageHeightMin: Optional[int] = Field(
        None, description='A minimum image height to search for.', example=720
    )
    imageLocation: Optional[GeoJSONSearchArea] = None
    imageNames: Optional[List[str]] = Field(
        None,
        description='Human readable names to search for.',
        example=['Image 43', 'Tractor in field'],
    )
    imageTimeStampRangeEnd: Optional[datetime] = Field(
        None, description='The latest timestamp to search for.'
    )
    imageTimeStampRangeStart: Optional[datetime] = Field(
        None, description='The earliest timestamp to search for.'
    )
    imageWidthMax: Optional[int] = Field(
        None, description='A maximum image width to search for.', example=1920
    )
    imageWidthMin: Optional[int] = Field(
        None, description='A minimum image width to search for.', example=1280
    )
    mimeTypes: Optional[List[constr(regex=r'image/.*')]] = Field(
        None,
        description='A set of image file types to search for.',
        example=['image/jpg', 'image/jpeg', 'image/gif'],
    )
    observationDbIds: Optional[List[str]] = Field(
        None,
        description='A list of observation Ids this image is associated with to search for',
        example=['47326456', 'fc9823ac'],
    )
    observationUnitDbIds: Optional[List[str]] = Field(
        None,
        description='A set of observation unit identifiers to search for.',
        example=['f5e4b273', '328c9424'],
    )


class Method(MethodBaseClass):
    methodDbId: Optional[str] = Field(
        None, description='Method unique identifier', example='0adb2764'
    )


class ObservationUnitPosition(BaseModel):
    entryType: Optional[EntryType] = Field(
        None,
        description='The type of entry for this observation unit. ex. "CHECK", "TEST", "FILLER"',
        example='TEST',
    )
    geoCoordinates: Optional[GeoJSON] = None
    observationLevel: Optional[ObservationUnitLevelRelationship] = None
    observationLevelRelationships: Optional[
        List[ObservationUnitLevelRelationship]
    ] = Field(
        None,
        description='Observation levels indicate the granularity level at which the measurements are taken. \n\n`levelName` defines the level \n\n`levelOrder` defines where that level exists in the hierarchy of levels. `levelOrder`s lower numbers are at the top of the hierarchy (ie field > 0) and higher numbers are at the bottom of the hierarchy (ie plant > 6). \n\n`levelCode` is an ID code for this level tag. Identify this observation unit by each level of the hierarchy where it exists',
        example=[
            {'levelCode': 'Field_1', 'levelName': 'field', 'levelOrder': 0},
            {'levelCode': 'Block_12', 'levelName': 'block', 'levelOrder': 1},
            {'levelCode': 'Plot_123', 'levelName': 'plot', 'levelOrder': 2},
        ],
    )
    positionCoordinateX: Optional[str] = Field(
        None,
        description='The X position coordinate for an observation unit. Different systems may use different coordinate systems.',
        example='74',
    )
    positionCoordinateXType: Optional[PositionCoordinateXType] = Field(
        None,
        description="The type of positional coordinate used. Must be one of the following values\n\nLONGITUDE - ISO 6709 standard, WGS84 geodetic datum. See 'Location Coordinate Encoding' for details\n\nLATITUDE - ISO 6709 standard, WGS84 geodetic datum. See 'Location Coordinate Encoding' for details\n\nPLANTED_ROW - The physical planted row number \n\nPLANTED_INDIVIDUAL - The physical counted number, could be independant or within a planted row\n\nGRID_ROW - The row index number of a square grid overlay\n\nGRID_COL - The column index number of a square grid overlay\n\nMEASURED_ROW - The distance in meters from a defined 0-th row\n\nMEASURED_COL - The distance in meters from a defined 0-th column",
        example='GRID_COL',
    )
    positionCoordinateY: Optional[str] = Field(
        None,
        description='The Y position coordinate for an observation unit. Different systems may use different coordinate systems.',
        example='03',
    )
    positionCoordinateYType: Optional[PositionCoordinateYType] = Field(
        None,
        description="The type of positional coordinate used. Must be one of the following values\n\nLONGITUDE - ISO 6709 standard, WGS84 geodetic datum. See 'Location Coordinate Encoding' for details\n\nLATITUDE - ISO 6709 standard, WGS84 geodetic datum. See 'Location Coordinate Encoding' for details\n\nPLANTED_ROW - The physical planted row number \n\nPLANTED_INDIVIDUAL - The physical counted number, could be independant or within a planted row\n\nGRID_ROW - The row index number of a square grid overlay\n\nGRID_COL - The column index number of a square grid overlay\n\nMEASURED_ROW - The distance in meters from a defined 0-th row\n\nMEASURED_COL - The distance in meters from a defined 0-th column",
        example='GRID_ROW',
    )


class ObservationVariable(VariableBaseClass):
    observationVariableDbId: str = Field(
        ...,
        description='Variable unique identifier\n\nMIAPPE V1.1 (DM-83) Variable ID - Code used to identify the variable in the data file. We recommend using a variable definition from the Crop Ontology where possible. Otherwise, the Crop Ontology naming convention is recommended: <trait abbreviation>_<method abbreviation>_<scale abbreviation>). A variable ID must be unique within a given investigation.',
        example='b9b7edd1',
    )
    observationVariableName: str = Field(
        ...,
        description='Variable name (usually a short name)\n\nMIAPPE V1.1 (DM-84) Variable name - Name of the variable.',
        example='Variable Name',
    )


class ObservationVariableNewRequest(VariableBaseClass):
    observationVariableName: str = Field(
        ..., description='Variable name (usually a short name)', example='Variable Name'
    )


class MethodSingleResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: Method


class ObservationListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationListResponseResult


class ScaleListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ScaleListResponseResult


class TraitListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: TraitListResponseResult


class ObservationVariableSingleResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationVariable


class MethodListResponseResult(BaseModel):
    data: List[Method]


class ObservationVariableListResponseResult(BaseModel):
    data: List[ObservationVariable]


class Image(ImageNewRequest):
    imageDbId: Optional[str] = Field(
        None, description='The unique identifier of an image', example='a55efb9c'
    )


class ObservationUnitNewRequest(BaseModel):
    additionalInfo: Optional[Dict[str, AdditionalInfo]] = Field(
        None, description='Additional arbitrary info'
    )
    externalReferences: Optional[ExternalReferences] = None
    germplasmDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies a germplasm',
        example='e9d9ed57',
    )
    germplasmName: Optional[str] = Field(
        None,
        description='Name of the germplasm. It can be the preferred name and does not have to be unique.',
        example='A0000001',
    )
    locationDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies a location, associated with this study',
        example='0e208b20',
    )
    locationName: Optional[str] = Field(
        None,
        description='The human readable name of a location associated with this study',
        example='Field Station Alpha',
    )
    observationUnitName: Optional[str] = Field(
        None,
        description='A human readable name for an observation unit',
        example='Plot 1',
    )
    observationUnitPUI: Optional[str] = Field(
        None,
        description='A Permanent Unique Identifier for an observation unit\n\nMIAPPE V1.1 (DM-72) External ID - Identifier for the observation unit in a persistent repository, comprises the name of the repository and the identifier of the observation unit therein. The EBI Biosamples repository can be used. URI are recommended when possible.',
        example='http://pui.per/plot/1a9afc14',
    )
    observationUnitPosition: Optional[ObservationUnitPosition] = None
    programDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies a program',
        example='2d763a7a',
    )
    programName: Optional[str] = Field(
        None,
        description='The human readable name of a program',
        example='The Perfect Breeding Program',
    )
    seedLotDbId: Optional[str] = Field(
        None,
        description='The unique identifier for the originating Seed Lot',
        example='261ecb09',
    )
    studyDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies a study within the given database server',
        example='9865addc',
    )
    studyName: Optional[str] = Field(
        None,
        description='The human readable name for a study',
        example='Purple_Tomato_1',
    )
    treatments: Optional[List[ObservationTreatment]] = Field(
        None,
        description='List of treatments applied to an observation unit.\n\nMIAPPE V1.1 (DM-74) Observation Unit factor value - List of values for each factor applied to the observation unit.',
    )
    trialDbId: Optional[str] = Field(
        None, description='The ID which uniquely identifies a trial', example='776a609c'
    )
    trialName: Optional[str] = Field(
        None, description='The human readable name of a trial', example='Purple Tomato'
    )


class ImageSingleResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: Image


class MethodListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: MethodListResponseResult


class ObservationVariableListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationVariableListResponseResult


class ImageListResponseResult(BaseModel):
    data: List[Image] = Field(..., description='Array of image meta data')


class ObservationUnit(ObservationUnitNewRequest):
    observationUnitDbId: Optional[str] = Field(
        None,
        description='The ID which uniquely identifies an observation unit\n\nMIAPPE V1.1 (DM-70) Observation unit ID - Identifier used to identify the observation unit in data files containing the values observed or measured on that unit. Must be locally unique. ',
        example='8c67503c',
    )
    observations: Optional[List[Observation]] = Field(
        None,
        description="All observations attached to this observation unit. \n\nDefault for this field is null or omitted. Do NOT include data in this field unless the 'includeObservations' flag is explicitly set to True.",
    )


class ImageListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ImageListResponseResult


class ObservationUnitSingleResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationUnit


class ObservationUnitListResponseResult(BaseModel):
    data: List[ObservationUnit]


class ObservationUnitListResponse(BaseModel):
    _context: Optional[Context] = Field(None, alias='@context')
    metadata: Metadata
    result: ObservationUnitListResponseResult
